language: python
cache: pip
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests
env:
  global:
    secure: pilAIsHSIFIHji55ikJzqOb6f5HpMUA7u/QRj2TQve0nBakxrzRXseCKA/frgyC0TSNyyanNGgYqScvMpL9JHbCNowUbyp0RzreIZ5UeMTBzRT1E4rBUZuZuWEKwJf/DA1fPWrpVf/4kKGHCv8KtfTyx/rczDJ07b73MW3ispJf7y72l7yZQjxdTsViLmK+4PZFHAGiXVkbVLt7JQVcf2O8a7VV+Ln36cws9elOat7DU722Unz9QLaOawPgxTxvmOnoRJWY4Nk9tEuPfg+pj9gci1tIPF9aZnAJ7zRnfplPL4KhMBJges9XytDUJl6doTKd8kPSlE/0GTeyDLqw2frKHQOcCgypJpt5smpzz4v49nJF7Rbb38ccZjC3F7LamRo5ZgV6gZvHFbehdNxIVj3sAbY+/H8mWYbpGHmbYm+lh9tois+ZTE4HOzJPkw1UCTtNuBs79SCZjsIfQDqTWUGQeaIXjwDCWVnmWcS5Sb0j0naiwYJMgtNq/f/GajRarNKtjJFLqVCb4wpUJBuf2y5GM3awr+h7FdLmAXBSuxQzblXiuLoNJ9Jh84gE+9K7vB87nCqxxlci6m8GH+Jq1YLFr1UwcaxyPZNBcRrFg2yYIQKN3VW+pw0Vi/M/SkfmgXki3iUGUnJsnz0yd++vUtNDGRlb7+bnPOemy2WKIZh0=
notifications:
  slack:
    secure: gqDhk71YXBNCD0WTh+p0ugBJpF6RvCbKM5QBO4PHXwB6Q4e6midinB09iGz4aP27UwR0yF4tq8F2VAbW38xHoyoTaUh6Z+mQC+pE+zk8Nb+vnmgYAOovbRzhCanxPOWOK5koo3TdlbV2PgcE/YKFXLQ8Lx3b95wdYKi1LQZ+mjejXlkohYNj7bzVzagX0bNAAhObuQrfkCLwkZsfZcHnp0oTeLgxGhj0O81W1nO/NFAt+uT5BSMXMuXsA3GyXuZW3N7OW9Og0dhVUak7W2Q1OS5A/inQ38JfS+sPefVHEqVxFG/cVjf6cB9X2sKgMgTorlLA+GjbYArj23ykU1CdSTs6eYgwvfrLsEXj1OlFEuqTwo8LeaKdjefqW50Fe5yxyAABh3sUbTIRikwdhV14nAm1Me+SQM4BNsn3zJ/JeGsl8ky6ytWHC90C3kzd/UJpY5jwhlme82tvDMgYKRxIW/x9D7JqQ8wVKJxaARDFpAcS0hhIHLQj2F1wNQli82LqQ5/TbiICMbfrzLuX1T1jjlV8T3JhfFgn4c7/pxLaPLLnGTXW1d+fisMebft3npqOR2foXxkhNN7q5IuV1I1iZuFQ0AnY6nT4DigWHGaFuJP90ZeZPN5isE4UYm1tJdFJ5GNbSfKbrv58f01p8RIeABgxm7MlaXkbqulVkQuwE+k=
    on_success: change
    template:
    - "@oncall"
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch}
      in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in
      %{duration}
  email:
    recipients:
    - devs-apex-alerts+travis@squareup.com
    on_success: change
